# Generated by Django 6.0 on 2026-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
