# Generated by Django 5.2.9 on 2026-01-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_hotel_description_en_hotel_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_status_en',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_status_ru',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_en',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_ru',
        ),
    ]
